### ISSUE TITLE
Translation status

### ISSUE THREAD

**Issue by Leronez** [translation-ru/vue-router#1]
## Status of translation by pages

- [x] vitepress config
- [x] main page and menu
- [x] Setup
  - [x] **(assigned to @Leronez)** #2
  - [x] **(assigned to @Leronez)**  #3
- [x] Essentials
  - [x] **(assigned to @Leronez)** #4
  - [x] **(assigned to @Leronez)** #5
  - [x] **(assigned to @Leronez)** #6
  - [x] **(assigned to @Leronez)** #7
  - [x] **(assigned to @Leronez)** #8
  - [x] **(assigned to @Leronez)** #9
  - [x] **(assigned to @Leronez)** #10
  - [x] **(assigned to @Leronez)** #11
  - [x] **(assigned to @Leronez)**  #12
  - [x] **(assigned to @Leronez)**  #117 
  - [x] **(assigned to @Leronez)**  #13
- [x] Advanced
  - [x] **(assigned to @Leronez)** #14
  - [x] **(assigned to @Leronez)** #15
  - [x] **(assigned to @Leronez)** #16
  - [x] **(assigned to @Leronez)** #17
  - [x] **(assigned to @Leronez)** #18
  - [x] **(assigned to @Leronez)** #19
  - [x] **(assigned to @Leronez)** #20
  - [x] **(assigned to @Leronez)** #21
  - [x] **(assigned to @Leronez)** #22
  - [x] **(assigned to @Leronez)** #23
  - [x] **(assigned to @Leronez)** #24
- [x] Migration
  - [x] **(assigned to @Leronez)** #25

**Comment by Leronez** [comment]
Для того, чтобы взять страницу в работу по переводу, выберите незанятую страницу, указанную в этой задаче (незанятая, значит названием не стоит подпись что кто-то назначен) и напишите в соответствующем issue об этом. Кто-то из мейнтейнеров закрепит задачу за вами, и укажет об этом в текущем issue.
